### ISSUE TITLE
Question - best practice for changing major version 

### ISSUE THREAD

**Issue by plumlee** [ajoberstar/gradle-git#106]
Appreciate your work on the plugin. We are using the [nebula-release-plugin](https://github.com/nebula-plugins/nebula-release-plugin) in our git strategy, with long lived release branches such as `release/1.x` that branch off `master`, and all feature branches coming off `master` as well. We build continuously off changes to `master` and use the release plugin to tag those.

 Looking at [https://github.com/ajoberstar/gradle-git/wiki/SemVer%20Support](https://github.com/ajoberstar/gradle-git/wiki/SemVer%20Support) in how versions are inferred semantically, it seems that one way to move to a new major version (from v1.x.y to v2.x.y) without having to create a release branch would be to manually tag a commit in master as `v2.0.0`. From this, the next build triggered in master should pick up that as the nearest tag, and all future builds would increment that tag.

My use case is that we might release version 1, and decide that our next release will be version 2, but we don’t cut our release branch until we get close to a release.

Do you have any other suggestions or better ways for properly using the inferred version? If this more properly belongs in the release plugin issues, I’ll post it there.

**Comment by ajoberstar** [comment]
If I'm reading this right, I think is solved by pretty straightforward use of the plugin:

1. Version 1.0.0 is released from release/1.x.
2. Changes (probably merged back into master.
3. Working in master, planning to start work on 2.0.
4. Run the release task with `-Prelease.scope=major` and some stage that will produce a tag. Looks like nebula bases stages on tasks (so `snapshot|devSnapshot|candidate`), Not sure if any of those besides candidate create a tag.
5. Now you have a 2.0.0-something.1 tag.
6. Work continues and builds now use a 2.0.0-... version.
6. Cut your release branch release/2.x.
7.  ...

You don't want to create a v2.0.0 tag because then you won't be able to release 2.0.0 later.

Let me know if that example didn't mesh with your use case.

**Comment by plumlee** [comment]
I hadn’t considered that making the `v2.0.0` tag meant we couldn’t use that as the actual release, good point. I’ll go with running the release task manually with a release.scope param like that. Thank you.
