### ISSUE TITLE
Question -- In a new project, how do I pre-seed default version to 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by dlethin** [ajoberstar/gradle-git#111]
When start a new project, with the defaulVersionStrategy set to SNAPSHOT, and no tags have been created in my repo, when I run gradle with no release.scope property, the default behavior sets the version to 0.0.1-SNAPSHOT

Is there a way through the plugin configuration to pre-seed the version so that it shows up as 1.0.0-SHAPSHOT?

Thanks.

**Comment by ajoberstar** [comment]
There aren't configuration options for this, but you could pre-seed the Git repository by creating a pre-release tag in the repository for 1.0.0-*. e.g. 1.0.0-dev.0+initial.seed. Otherwise I think you could do this using a [release branch](https://github.com/ajoberstar/gradle-git/blob/23eb7386d3f53b381a1a1f6a91fcef2e747deec5/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy#L81).

**Comment by dlethin** [comment]
Thanks.  I will look into your suggestions.
