### ISSUE TITLE
versionCode?

### ISSUE THREAD

**Issue by paleozogt** [ajoberstar/gradle-git#131]
When doing Android development, there's a "versionName" (a string) as well as a "versionCode" (a monotonically increasing int).

I typically use gradle-git's ```project.version``` for the "versionName", and cook up my own "versionCode" by looking at how many commits have been made:
```
ext.git = Grgit.open(projectDir)
ext.versionCode = git.log().size()
```

This seems to be a fairly [common technique](http://12rockets.com/journal/versioning-system-with-git-and-gradle/) in the Android community.

Of course, I have to remember to copy this gradle code into all of my projects.  I wonder: could we have gradle-git do this automatically?

**Comment by ajoberstar** [comment]
So you're thinking of something like this?

```groovy
plugins.withId('whatever.the.android.id.is') {
  versionCode = grgit.log.size()
}
```

That could make sense in a plugin, but if you're using `org.ajoberstar.grgit` along with `org.ajoberstar.release-{base|opinion}` your original block is really just a one liner since the `grgit` property is already populated.

I'm hesitant to put this in gradle-git, since I'm not familiar with Android development (let alone their Gradle plugin) and am not sure what other configurability might be of benefit (if any).

If you have some other thoughts, let me know. Right now I'm leaning towards calling this a "won'tfix".

**Comment by paleozogt** [comment]
No problem-- I just thought I'd throw it out there.

**Comment by ajoberstar** [comment]
Alright. Thanks for posting the idea.
