### ISSUE TITLE
for native build the plugin effectively disables buildType { release } variant

### ISSUE THREAD

**Issue by marmax** [ajoberstar/gradle-git#181]
If I try to apply the release plugin on a project with native components (i.e. c/c++), then if there is a model block

> buildTypes {
>    debug
>    release
> }

the plugin effectively disables/removes the "release" build type variant.

The problem can be demonstrated using this sample project https://github.com/marmax/gradle-release-plugin-buildtype-bug/

M.

**Comment by ajoberstar** [comment]
That's odd, particularly given I don't interact with the model at all. I wonder if a buildType that matches any existing task name would have the same behavior.

**Comment by ajoberstar** [comment]
After some looking when #211 after submitted, it appears that [Gradle's plugin tries to configure a task](https://github.com/gradle/gradle/blob/master/buildSrc/src/main/groovy/org/gradle/plugins/buildtypes/BuildTypesPlugin.groovy#L30) with the build type's name. 

I think Gradle should be throwing an exception if two tasks exist with the same name, instead of causing the subtle differences you are seeing. 

Renaming gradle-git's task/extension is possible, but that's a breaking change that I don't want to make lightly. It likely won't happen until I have other reasons to make a 2.0.

I'll close this as a won't fix from my perspective, but would suggest reporting the issue [to Gradle on their forum](https://discuss.gradle.org/) to have the exception raised in this scenario.

Let me know if you have any alternate thoughts.

**Comment by marmax** [comment]
Hi @ajoberstar,

I think you are wrong on your reasoning - the BuildTypesPlugin you are referring to is a part of Gradle's own buildSrc, thus is hardly a part of released Gradle and can't affect any 3rdparty build.

Anyway, I will try to find the real source of the problem and will let you know...

**Comment by ajoberstar** [comment]
Good catch, wasn't paying close enough attention.

**Comment by ajoberstar** [comment]
Feel free to reopen if you identify the source of this.
