### ISSUE TITLE
Poor Documentation

### ISSUE THREAD

**Issue by mrgmatthews** [ajoberstar/gradle-git#184]
So tasks were removed in an older version.

There doesnt seem to be good docs around how to use this plugin.

What would be the equivalent of the following:

	plugins {
		id "org.ajoberstar.grgit" version "1.5.0"
	}
	import org.ajoberstar.grgit.*
	
	task cloneGitRepo(type: GitClone) {
		delete "third-party-libs/repo"
		credentials {
			username "${propsUsername}"
			password "${propsPassword}"
		}
		def destination = file("third-party-libs/repo")
		uri = "git@bitbucket.org:comcat/repo.git"
		destinationPath = destination
		bare = false
	}

**Comment by mrgmatthews** [comment]
tried
	task cloneGitRepo {
		delete 'third-party-libs/repo'
		def credentials = new org.ajoberstar.grgit.Credentials("${cafexRepoUsername}","${cafexRepoPassword}")
		Grgit.clone(dir: file('third-party-libs/repo'), uri: 'git@github.com:cafexcomms/sa-main.git', credentials: credentials)
		
	}

with no luck, get the error
Can't obtain updateLastError method for class com.sun.jna.Native

**Comment by ajoberstar** [comment]
I'd start by making sure you're on the latest version (1.5.0, noted on the README). This will also make sure you're on the latest version of [Grgit](https://github.com/ajoberstar/grgit). There is documentation in [the wiki](https://github.com/ajoberstar/gradle-git/wiki) on the basic use case, which is usually interacting with the repo of the current Gradle project.

I believe the error you're seeing was resolved quite a while back, so the latest Grgit should get past that. However, your task is also needs to look more like the example in [Grgit Usage](https://github.com/ajoberstar/gradle-git/wiki/Grgit%20Usage). Currently, you are running the clone during the configuration phase of Gradle, rather than the execution one. This means it will clone that repo whether you run the task or not.

```groovy
task cloneGitRepo {
  ext.credentials = ...
  doLast {
    delete 'repo-dir'
    Grgit.clone(dir: 'repo-dir', uri:'...', credentials: credentials)

  }
}
```

**Comment by mrgmatthews** [comment]
Awesome, my bad. Hope this helps someone else in the future
