### ISSUE TITLE
Obscure bug in release plugin

### ISSUE THREAD

**Issue by itissid** [ajoberstar/gradle-git#206]
I am using the shadow jar and the release plugin. Basically it is a jar task and makes the fat jar.

An obscure bug happens only when my repo is clean, release strategy final/dev: The publication task that uploads the jar gets confused about the name and tries adding a classifier string `-all` at the end: 

```
 Invalid publication 'shadow': artifact file does not exist: '/home/sid/workspace/sandbox/build/libs/test-project-0.1.0-all.jar'
```

But the actual classifier is null and the real file is `test-project-0.1.0.jar`

This does not happen when release plugin is removed and also does not happen if the repo is dirty. The default versionStrategy is a custom one that increments the minor scope of the plugin. 
So what is it about the dirty repo that might effect the shadow plugin?

I would be happy to upload a test project for you to play with, if you have the bandwidth.

Gradle 2.12
Release plugin 1.4.2

**Comment by ajoberstar** [comment]
I might be able to take a look this weekend, if you want to upload the test project.

**Comment by ajoberstar** [comment]
After some looking when #211 after submitted, it appears that [Gradle's plugin tries to configure a task](https://github.com/gradle/gradle/blob/master/buildSrc/src/main/groovy/org/gradle/plugins/buildtypes/BuildTypesPlugin.groovy#L30) with the build type's name. 

I think Gradle should be throwing an exception if two tasks exist with the same name, instead of causing the subtle differences you are seeing. 

Renaming gradle-git's task/extension is possible, but that's a breaking change that I don't want to make lightly. It likely won't happen until I have other reasons to make a 2.0.

I'll close this as a won't fix from my perspective, but would suggest reporting the issue [to Gradle on their forum](https://discuss.gradle.org/) to have the exception raised in this scenario.

Let me know if you have any alternate thoughts.

**Comment by ajoberstar** [comment]
If you end up wanting to publishing a test project, please reopen and include a link.
