### ISSUE TITLE
Another question: release.stage=patch vs no release.stage defined 

### ISSUE THREAD

**Issue by kknd22** [ajoberstar/gradle-git#208]
Great help. Got another question, for an existing git repo. we start midway to use this plugin.
there are some old releases which do not follow the SemVer tags conventions.
scenarios: 
- reachable tags are: `v1.2.0-rc.1, v1.2.0-milestone.1`
- closest final tag is: ` v1.0.0`
if do `-Prelease.stage=rc `then the inferred version is` v.1.2.0-rc.2,` which is correct
but do` -Prelease.stage=rc -Prelease.scope=patch`, then the inferred version is` 1.0.1-rc.1`

and encounter error
`Inferred version (1.0.1-rc.1) cannot be lower than nearest (1.2.0-milestone.1). Required by selected strategy`

Two more question: 
1. if patch is the default, why the different behavior.
2. what's the best strategy to "seed" an existing git repo start with a higher version e.g. 2.3.x

Thanks
-cl

**Comment by ajoberstar** [comment]
Short version is [details in this code](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy):

- There are two nearest tagged versions detected: the absolute nearest (1.2.0-rc.1) and the nearest final release (1.0.0)
- If you provide `release.scope` it increments from the nearest final.
- If you don't provide the property, and the "normal" component of the absolute and final nearests are different (1.0.0 != 1.2.0), it assumes you're in the middle of working on a new release, so it keeps the same normal you've been making pre-release versions of (1.2.0).
- Otherwise it falls back to a default value for `release.scope` (patch with opinion) 

Normally, you're not going to run into a case where you release a `minor` pre-release and then decide it's just going to be a `patch`. The strategies configured by opinion are configured to enforce version precedence, so that you are always moving the versions forward. Might not always be right for everyone's situation.

If you want to seed a version, the simplest way is to add a tag with the version you'd want to increment from. Only issue is that it might be misleading if that version wasn't actually released. I haven't had a lot of requests for this, so if you have some better thoughts on how this could be made available, let me know.

**Comment by ajoberstar** [comment]
Please reopen if you have further questions.
