### ISSUE TITLE
Migrating from Snapshot to Development strategy

### ISSUE THREAD

**Issue by r2edondo** [ajoberstar/gradle-git#212]
I had this configuration: 

```
versionStrategy FINAL
versionStrategy PRE_RELEASE
defaultVersionStrategy  SNAPSHOT
```

And now I am trying to move to this one:

```
versionStrategy FINAL
versionStrategy PRE_RELEASE
defaultVersionStrategy  DEVELOPMENT
```

Doing some testing I found a bug already reported in [issue 210](https://github.com/ajoberstar/gradle-git/issues/210), now I'm facing a new problem, see the table below:

```
git describe
v0.2.0
```

| steps | attributes | snapshot v. | dev v. | expected dev v. |
| --- | --- | --- | --- | --- |
| 1 ok | patch snap/dev | 0.2.1-SNAPSHOT | 0.2.1-dev.1+11aa | 0.2.1-dev.1+11aa |
| 2 ok | patch rc | 0.2.1-rc.1 | 0.2.1-rc.1 | 0.2.1-rc.1 |
| 3 ups! | patch snap/dev | 0.2.1-SNAPSHOT | 0.2.1-**rc.1**.dev.1+11aa | 0.2.1-dev.1+11aa |
| 4 ok | patch rc | 0.2.1-rc.2 | 0.2.1-rc.2 | 0.2.1-rc.2 |
| 5 ok | _new commit pushed_ |  |  |  |
| 6  ups! | patch snap/dev | 0.2.1-SNAPSHOT | 0.2.1-**rc.2.dev.1**+22bb | 0.2.1-**dev.2**+22bb |

When I release the same commit in step 3 I expect to obtain the same dev version that I have in step 1. And when I push more commits in step 5, I expect my dev version to reflect this new commit. In summary, I think both differences share a common question: Is there any reason not to infer the DEV version against the last FINAL version instead of the latest PRE_RELEASE version?

Thanks!

**Comment by ajoberstar** [comment]
For step 3... generally `gradle-git` is trying to make sure that a version is always greater than or equal to the previous one. Since your last release was `rc.1`, we need to make sure your dev release is sorted after that (by SemVer rules). There are a few cases where that doesn't hold true, but they're not very common.

For step 5... the development strategy uses [this counting logic](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy#L236). It's always counting from your last version (not the last final release). You could easily adapt that `COUNT_COMMITS_FROM_ANY` to go from the normal if you don't like the defaults.
