### ISSUE TITLE
dependency-ranges: x.y.z-milestone.m.dev.n+xx not taken as latest version, but x.y.z-milestone.m is used

### ISSUE THREAD

**Issue by gerhard6** [ajoberstar/gradle-git#223]
Hello

I wonder about this:

my list of artifacts in local maven repo 

	5.1.1-milestone.2.dev.1+978b414/
	5.1.1-milestone.3/
	5.1.1-milestone.3.dev.1+380931b/
	5.1.1-milestone.3.dev.2+d0291de/
	5.1.1-milestone.3.dev.3+6175bcf/
	5.1.1-milestone.4/
	5.1.1-milestone.4.dev.1+f6e7805/
	
so, 5.1.1-milestone.4.dev.1+f6e7805 is newer (later commit) than 5.1.1-milestone.4

on the other project I have such a dependency version-range:
   
    compile 'ggg:aaa:5.1.1+'

and the unintended result is that this references the milestone.4 version and not the milestone.4.dev.1 version

is this a bug or by design ? 

If by design, then: How should I define my dependency to stay always with the latest version ?
Am I using the wrong approach ? - if yes, would you have some pointers to guidelines for me ?

How could I adapt your code/config to achieve the intended result ?

IMO a better strategy would be to have a sequence like this:

	5.1.1-milestone.3.dev.1+380931b/
	5.1.1-milestone.3.dev.2+d0291de/
	5.1.1-milestone.3.dev.3+6175bcf/
	5.1.1-milestone.3/
	5.1.1-milestone.4.dev.1+f6e7805/
	5.1.1-milestone.4/

Thx a lot, Gerhard

**Comment by ajoberstar** [comment]
This is by design (mostly). gradle-git is using version numbers that comply with and sort appropriately using [SemVer](http://semver.org/spec/v2.0.0.html) (see pt. 11 in the spec). In SemVer, `5.1.1-milestone.3.dev.3+6175bcf` has higher precedence than `5.1.1-milestone.3`. Gradle uses a different sorting approach were having more segments to your version means lower precedence. It's unfortunate to lose the dependency ranges, but I wanted to stick with SemVer's spec. 

I've [reported this to Gradle in the past](https://discuss.gradle.org/t/gradles-version-comparison-violates-semver/10550/2), and it doesn't sound like they have plans to do anything in the near future, and I haven't had time to look at it either.

**Comment by ajoberstar** [comment]
To work around this, you'd probably need to build up your own strategies that would create the versions as you suggested. Take a look through the [Strategies](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy) source to see how the current stuff works. You can probably just mix and match to get what you're looking for.
