### ISSUE TITLE
Tags on branch are taking into consideration when inferring next tag on master

### ISSUE THREAD

**Issue by dbahlbeck** [ajoberstar/gradle-git#230]
Hi,
I have a simple repo with a few changes. The git log looks like this:
```
* f0fe9f8 (HEAD -> master, origin/master) change message to goodbye
| * 1563b34 (tag: v0.2.0, origin/foo, foo) change message to hello world
|/  
* 44212bb (tag: v0.1.0) add code
* 6ceef32 add code and gradle files
* b928c2f add readme
```
As you can see I made a release on the branch using:
 `./gradlew release -Prelease.scope=minor -Prelease.stage=final`

Now when I try to release on master with the same command it tries to re-release `0.2.0` instead of taking the next available version number `0.3.0`. The error I get is:
```
Caused by: org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={
object f0fe9f875b1ad805d020cc7cea6f1ff26fe92cb1
type commit
tag v0.2.0
tagger PersonIdent[Me, my-email@somewhere, Mon Nov 21 08:48:51 2016 +0100]

Release of 0.2.0

- change message to goodbye
}' already exists
        at org.eclipse.jgit.api.TagCommand.updateTagRef(TagCommand.java:193)
        at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:164)
        at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:91)
        at java_util_concurrent_Callable$call$0.call(Unknown Source)
        at org.ajoberstar.grgit.operation.TagAddOp.call(TagAddOp.groovy:119)
        ... 72 more
```

Is this the expected behaviour when branches get tagged or a possible bug?

Regards,
David

**Comment by ajoberstar** [comment]
This is expected behavior. There's an assumption that a 0.3.0 would build on the history of 0.2.0. A 0.2.1 could branch off and be unrelated to 0.3.x.

There's a lot of details still to be worked out on exactly how branches should relate to each other when it comes to versioning. See #115 for some of this discussion. I haven't worked on it much recently and any major changes are likely to end up in [semver-vcs](https://github.com/ajoberstar/semver-vcs) rather than here.
