### ISSUE TITLE
Using grgit when project is used as git submodule in other project

### ISSUE THREAD

**Issue by Barteks2x** [ajoberstar/gradle-git#236]
I use grgit to create version number from tags, branch name and output of git describe in 2 projects. Versions have different format in both of these projects.

I want to include one of these projects as git submodule in the other one and add it as gradle project dependency. The problem I get is that grgit will open repository of the main project instead of the submodule, which won't produce correct version number (or any version at all because tag format is wrong).

When I try to directly open projectDir it still fails because it can't find the repository (apparently submodule is not a repository). How to make it use the submodule instead?

**Comment by Barteks2x** [comment]
After reading that link, I'm not exactly sure how composite build would help here, and how exactly I would be able to avoid using submodule there. Also based on that, composite builds won't work properly in any IDE.

**Comment by ajoberstar** [comment]
Sure, I can try and explain that more. If I'm understanding you correctly, you have two separate repositories which were previously independent Gradle builds. You want to compile against the latest code rather than download a pre-compiled JAR. Composite builds let you combine two projects essentially just for the purpose of swapping that normal Maven dependency for a project dependency. IDE support is still light, in my understanding.

Basically, my point was just that this is a way using existing features of Gradle that might get you the behavior you want. Anything beyond that would require an enhancement to Grgit to support submodules to whatever level JGit currently allows, which I haven't investigated  yet.

If you prefer that route, please file an issue for [Grgit](https://github.com/ajoberstar/grgit/issues) being as specific as you can about what submodule functionality you would need for your use case.

**Comment by Barteks2x** [comment]
First I would need to get the second project into some maven repository. It's currently in very early development and it's very small library that I made separate because I know for certain other project that want to read files produced by it will eventually need that library.

I'm also not sure if [gradle-script-kotlin](https://github.com/gradle/gradle-script-kotlin) currently supports composite builds.

For now I can just silence the warning about wrong version format and ignire wrong version of that library.

**Comment by dalbertom** [comment]
I think the underlying issue here is that in git the `.git` directory can actually be a file whose contents are `gitdir: /path/to/file`. There are several cases where this occurs: using git submodules, using git worktrees or cloning with the --separate-git-dir option.

I haven't spent much time looking at the jgit code, but it does include a constant set to 'gitdir:' in https://github.com/eclipse/jgit/blob/v4.6.1.201703071140-r/org.eclipse.jgit/src/org/eclipse/jgit/lib/Constants.java#L415 which is used in https://github.com/eclipse/jgit/blob/v4.6.1.201703071140-r/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/FileRepository.java#L369

**Comment by stevemenke** [comment]
I am having the same problem. I have a gradle/git project  structure as follows:

-parent
|--app(submodule)
|--lib (submodule)

If I build app or lib I get the git hash from the parent not from the submodule. Has a ticket been filed for this or is there a workaround?
