### ISSUE TITLE
describe() works different from git describe

### ISSUE THREAD

**Issue by childnode** [ajoberstar/gradle-git#260]
While `git describe` uses annotated tags only per default, Grgit.describe() behaves like `git describe --tags`

Would be great default would behave the same way and --tags to resolve leightweight tags would be an option.

Another case is the `git describe --dirty` case which seems to be impossible to get with grgit too atm?!

**Comment by ajoberstar** [comment]
gradle-git, relies on grgit, which in turn relies on JGit. JGit's [DescribeCommand](http://download.eclipse.org/jgit/site/4.8.0.201706111038-r/apidocs/org/eclipse/jgit/api/DescribeCommand.html) currently doesn't seem to provide any configurability to address this, so until that's enhanced you'll have to find an alternate solution.

Since this is a grgit issue rather than gradle-git, I'll close this out. If there is an issue open (or you open a new one) with JGit that you want to tie this request to, please open a new issue on the [grgit](https://github.com/ajoberstar/grgit) repo so it can be tracked.

**Comment by childnode** [comment]
indeed, the relevant issue is here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=423206
thanks anyway for pointing out (even it was obvious ;) )

**Comment by childnode** [comment]
FYI: pending change in jgit https://git.eclipse.org/r/115690

**Comment by childnode** [comment]
@ajoberstar 
FYI: change is approved and upcoming in jgit 5.0

**Comment by ajoberstar** [comment]
Thanks for the update. This should get resolved with ajoberstar/grgit#233.
