### ISSUE TITLE
problem using the plugin

### ISSUE THREAD

**Issue by Wizzzo** [ajoberstar/gradle-git#265]
i've tried using the plugin on my gradle project, and i've got the following problem.
https://stackoverflow.com/questions/45275731/clone-git-repository-on-my-gradle-using-grgit

**Comment by Wizzzo** [comment]
hello, i really need to ask you a question, can you contact me please?

**Comment by ajoberstar** [comment]
Hi, @Wizzzo. I try to get to issues as I have time, but this is just an open source side project, I can't always respond in a timely manner.

Since you've already asked the question on StackOverflow, I'd like to keep the discussion there. Particularly since someone has already taken the time to provide an answer, could you either provide comments to his answer explaining what he hasn't addressed or mark it accepted if it meets your needs?

**Comment by Wizzzo** [comment]
Thanks @ajoberstar, i've found another problem, that occurs if i'm using the grgit plugin with the credentials plugins "classpath "nu.studer:gradle-credentials-plugin:1.0.1" the problem occure as soon as i'm adding the classpath of the grgit (version 1.7.2), i'm not even when i'm not applying the plugin.
have you ever experience this issue

**Comment by ajoberstar** [comment]
To make this more discoverable for anyone who encounters this in the future, please open this as a new issue. Please also provide more details in the issue:

- version of Gradle
- include a snippet (or the full) `build.gradle`
- output from Gradle showing the error (use gradle's the `--stacktrace` flag)

I'm not familiar with the credentials plugin, so I can't say yet whether it's something I'll be able to help with.
