### ISSUE TITLE
grgit dependency is outdated

### ISSUE THREAD

**Issue by elestedt** [ajoberstar/gradle-git#271]
I'm in a project where we need to use both grgit and the release plugin. This causes a problem because we need a newer version of the grgit plugin than the gradle-git plugin is referrencing.
I tried to include both grgit and gradle-git in the project, but understandably gradle can't instanciate them.

Specifically what we need access to is the grgit.Tag.dateTime property, which isn't available in the version of grgit currently referenced by the latest release of gradle-git.

**Comment by ajoberstar** [comment]
As, you may have already seen in the [README](https://github.com/ajoberstar/gradle-git/blob/master/README.md) I've broken gradle-git up into component plugins each in their own repo. grgit 2.x is no longer (at least not intentionally) compatible with gradle-git since it now contains the `org.ajoberstar.grgit` Gradle plugin.

You may want to evaluate [reckon](https://github.com/ajoberstar/reckon) as a replacement for the release plugin. The documentation still needs work, but it's intended to support the same version inference capabilities.

If reckon won't work for you, I'd be interested in feedback about its shortcomings.

**Comment by elestedt** [comment]
Reckon would work for setting the version of apps - but it won't tag and push tags.

**Comment by ajoberstar** [comment]
Sorry for the delay. That's an omission from the documentation. The [plugin](https://github.com/ajoberstar/reckon/blob/master/reckon-gradle/src/main/java/org/ajoberstar/reckon/gradle/ReckonPlugin.java) adds `reckonTagCreate` and `reckonTagPush`. It will only tag _significant_ versions and the push will only push the tag (gradle-git would push the current branch too).

**Comment by elestedt** [comment]
That might resolve it - though I'm reluctant to try and infer the functionality from the source code. Especially when the documentation on this repo states that reckon "will not pretend to be a full-featured release plugin"...

**Comment by ajoberstar** [comment]
I'm hoping to get to doc improvements in reckon soon (ajoberstar/reckon#58).

I'll close this as a won't fix, since reckon's the direction I'm planning to maintain.
