### ISSUE TITLE
How to use RebuildVersionStrategy

### ISSUE THREAD

**Issue by cdancy** [ajoberstar/gradle-git#273]
My issues is similar to #188 but the links on that PR seem to be dead. We're putting together the [gradle-kubernetes-plugin](https://github.com/bmuschko/gradle-kubernetes-plugin) and want to to be able to trigger a new version/tag from the desktop but then in a CI environment, in our case travis-ci, we still want to run the `release` task but to use the existing version. 

Our code is all within our root build.gradle file [HERE](https://github.com/bmuschko/gradle-kubernetes-plugin/blob/master/build.gradle). I've followed the instructions on the wiki here and from other sources and still can't seem to get things to work properly. Running with `--info` I get:
```
Skipping rebuild strategy because clean is true, "release." properties are true and head version is null
Skipping development strategy because stage (SNAPSHOT) is not one of: [dev]
Skipping pre-release strategy because stage (SNAPSHOT) is not one of: [milestone, rc]
Skipping final strategy because stage (SNAPSHOT) is not one of: [final]
Using snapshot default strategy because repo is clean and no stage defined
Falling back to default strategy: snapshot
```
I don't understand why rebuild strategy is getting skipped. When I do a `git tag` locally I see the `v0.0.1` present so not sure why it's not getting picked up and instead falling back to the snapshot version. 

Any ideas?

**Comment by ajoberstar** [comment]
So it looks like 2 issues looking at [the logic](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/semver/RebuildVersionStrategy.groovy):

1. `"release." properties are true` implies that you are providing the `release.scope` or `release.stage` properties. (This behavior is due to #68.)
2. `head version is null` implies that it can't find a tag on `HEAD` that it considers a version tag. (Not sure why it would think that.)

I think the main thing you'll want to change is removing [this block](https://github.com/bmuschko/gradle-kubernetes-plugin/blob/master/build.gradle#L25) that sets `release.stage` and `release.scope`. If you provide either, the plugin assumes you're trying to influence the version and will always try to increment.

**Comment by cdancy** [comment]
My apologies ... this turned out to be a silly gradle issue on my end. I assumed that:
```
gradle.properties
    ciRelease=false

build.gradle
    if (ciRelease) {
         println "should never get here"
    }
```
the line `should never get here` would be reached but I had forgotten that gradle would treat the property as a boolean until it is cast as one and so was entering that code block every time.

Thanks for taking a look anyway and great work on the plugin.
