### ISSUE TITLE
Version number unexpectedly decorated on 'release' builds

### ISSUE THREAD

**Issue by ojacobson** [ajoberstar/gradle-git#96]
When building a project using the `release-opinion` plugin, version numbers for release builds are decorated with `-dev.COUNT+HASH`. Steps to reproduce:

```groovy
import org.ajoberstar.grgit.Grgit

buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath group: 'org.ajoberstar', name: 'gradle-git', version: '0.12.0'
  }
}

apply plugin: 'java'
apply plugin: 'org.ajoberstar.release-opinion'

group = 'com.example'

release {
  grgit = Grgit.open(file('.'))
}

tasks.release {
  dependsOn 'build'
}
```

Built on a pristine repo, with no tags:
```
$ git describe --tags --always
e84268c

$ gradle -q release
$ ls build/libs
gradle-git-sandbox-0.0.1-dev.1+e84268c.jar
```

Built on a repo with the current revision tagged:
```
$ git tag -m 'Test' v0.0.1
$ git describe --tags --always
v0.0.1

$ gradle -q release
$ ls build/libs
gradle-git-sandbox-0.0.2-dev.0+e84268c.jar
```

I was expecting, based on the documentation, for at least one of those two builds to have the version `0.0.1` with no decoration (probably the first of the two). I'm not sure whether my expectations are wrong or I've misconfigured something - help?

**Comment by ajoberstar** [comment]
A little bit of expectations and a little bit of a limitation of `gradle-git`. This changes with `0.13.0` (see the [Release Notes](https://github.com/ajoberstar/gradle-git/wiki/Release%20Notes)) which has only been released as a milestone so far (`0.13.0-milestone.1`).

Now a build against a commit tagged with a version will use that version, unless you are asking for it to be different using `release.scope` or `release.stage`.

The first build is working as expected. It will select the `DEVELOPMENT` strategy (hence the `-dev.<commits>+<hash>`) if it doesn't have anything else to go on. Since there are no other tags it's using the default `PATCH` scope (hence the `0.0.1`).

Let me know if you have any other questions.

**Comment by ojacobson** [comment]
It looks like 0.13.0-milestone.1 behaves "how I expect" for this case:

```
$ git tag -m 'Test' v0.0.1
$ git describe --tags --always
v0.0.1

$ gradle -q release
$ ls build/libs
gradle-git-sandbox-0.0.1.jar
```

Where can I read more about `release.scope` and `release.stage` and how they change the behaviour of the plugin? I didn't see anything obvious in the wiki; should I RTFS? Did I miss it, like a dummy?

Either way, thanks for getting back to me. Much appreciated!

**Comment by ajoberstar** [comment]
The docs aren't in the best state, but this is the page that describes the [release.scope and release.stage](https://github.com/ajoberstar/gradle-git/wiki/SemVer%20Support).

**Comment by ajoberstar** [comment]
I plan to make them better before going 1.0.
